name: Build and Deploy Frontend

on:
  push:
    branches:
      - "main"
    paths:   
      - 'career-flow-ui/**'
  pull_request:
    branches:
      - main
  schedule: 
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install dependencies
        run: npm install
        working-directory: career-flow-ui/
      - name: Build
        run: npm run --silent build
        working-directory: career-flow-ui/
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: career-flow-ui/build # The folder the action should deploy.
